name: gh-pages branch build

on:
  push:
    branches:
      [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4.2.2 
        with: 
          ref: 'main'

      - name: Test
        run: cat ./planet-sim/Cargo.toml
